dtable_events/activities/notification_rules_per_update_utils.py
dtable_events/app/app.py
dtable_events/dtable_io/dtable_io_server.py
dtable_events/dtable_io/utils.py
dtable_events/main.py

Reverts seatable/dtable-events#63

Revert "update_conf_url"

---

dtable_events/activities/notification_rules_utils.py
dtable_events/tasks/dtable_notification_rules_scanner.py

Deal invalid notification

---

dtable_events/automations/actions.py
dtable_events/automations/general_actions.py
dtable_events/notification_rules/message_formatters.py
dtable_events/notification_rules/notification_rules_utils.py
dtable_events/notification_rules/utils.py
dtable_events/utils/constants.py
dtable_events/utils/dtable_db_api.py

init message formatters
opt formatters
debug formatter
opt formatters
opt sql rows formatters
opt code
remove useless code
remove useless code

near deadline rows from dtable-db and format these

---

dtable_events/automations/actions.py
dtable_events/dtable_io/__init__.py
dtable_events/dtable_io/utils.py
dtable_events/utils/sql_generator.py

1. fix ex-import base auto rule trigger-workflow action use old workflow token bug
2. fix auto rule which only has trgger-workflow action doesn't update last_trigger_time bug
3. fix filter2sql transfer invalid view filters to empty-string sql bug

fix several bugs

---

dtable_events/data_sync/data_sync_utils.py

add required column, Emails in Threads table ,check before run email-sync

add required column, Emails in Threads table

---

dtable_events/dtable_io/import_table_from_base.py

as the description of the title

fest: import base from table support views

---

dtable_events/utils/sql_generator.py

fix:add department filter_term

fix:add department filter_term

---

dtable_events/utils/sql_generator.py

Reverts seatable/dtable-events#633

Revert "fix:add department filter_term"

---

dtable_events/utils/sql_generator.py

fix trend sql

---

dtable_events/utils/sql_generator.py

Fix show statistic detail conditions

Fix show statistic detail filter conditions

---

dtable_events/utils/sql_generator.py

 fix: update department filter

---

dtable_events/utils/constants.py
dtable_events/utils/sql_generator.py

Support funnel chart

---

dtable_events/utils/constants.py
dtable_events/utils/sql_generator.py

Support table element in statistic api

Support table element in statistic api

---

dtable_events/dtable_io/__init__.py
dtable_events/dtable_io/request_handler.py
dtable_events/dtable_io/task_manager.py
dtable_events/dtable_io/utils.py

add export-big-data-screen-app

add export-big-data-screen-app

---

dtable_events/automations/actions.py

support table's formula with array result type match other table column

opt per-update link-records 

---

dtable_events/utils/sql_generator.py

fix: completeness chart sql

---

dtable_events/utils/sql_generator.py

support filter group

---

dtable_events/utils/sql_generator.py

support start of week in statistic

support start of week in statistic

---

dtable_events/activities/db.py
dtable_events/dtable_io/excel.py
dtable_events/dtable_io/utils.py

- query activity in 5 mins, drop order
- fix convert-to-excel when handle formula
- read inner_file_server_root from app.config

fix record activities, convert-to-excel, gen_inner_file_get_url

---

dtable_events/automations/actions.py
dtable_events/dtable_io/excel.py

- fix auto-rule retry sql query
- fix wrong value in formula cell with non-format date when export as excel

fix auto-rule sql-query retry, convert to excel
